### ISSUE TITLE
Sample project error on registering a new user

### ISSUE THREAD

**Issue by erveloso** [francnuec/Neo4j.AspNetCore.Identity#1]
I just tried to run the sample project and it returns the following error on registration:

> ArgumentNullException: Value cannot be null.
Parameter name: entityType
Neo4jClient.DataAnnotations.EntityService.AddEntityType(Type entityType)

Microsoft.AspNetCore.Identity.UserManager<TUser>.UpdateUserAsync(TUser user)
Microsoft.AspNetCore.Identity.UserManager<TUser>.AddClaimsAsync(TUser user, IEnumerable<Claim> claims)
Neo4j.AspNetCore.Identity.Sample.Controllers.AccountController.Register(RegisterViewModel model, string returnUrl) in AccountController.cs

**126.       await _userManager.AddClaimAsync(user, new Claim(ClaimTypes.Role, "User"));**

Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()

I'm using Neo4j 3.5.2 on Windows 10.
Any idea on how to fix this? Thanks.

**Comment by francnuec** [comment]
Hi @erveloso. I think I haven't updated this sample in a while and quite a lot has changed. My bad. I will try to update now and then you can pull the changes.

**Comment by francnuec** [comment]
You can check now. It was actually a bug in the underlying library (Neo4jClient.DataAnnotations), so thanks much for this.
